project:
  type: website
  output-dir: docs

website:
  title: "microbial culture technology"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    mainfont: Noto Sans, sans-serif
    css: styles.css

editor: visual

